version: '3'

services:
  mongo:
    image: bitnami/mongodb:4.2.3
    container_name: mongo
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MONGODB_ROOT_PASSWORD=${MONGO_PASS_ROOT}
      - MONGODB_USERNAME=${MONGO_USER}
      - MONGODB_PASSWORD=${MONGO_PASS}
      - MONGODB_DATABASE=${MONGO_DATABASE}
    volumes:
      - mongo:/bitnami/mongodb/data
    ports:
      - '${MONGO_PORT}:27017'

  redis:
    image: bitnami/redis:4.0.14
    container_name: redis
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis:/bitnami/redis/data
    ports:
      - '${REDIS_PORT}:6379'

volumes:
  mongo:
  redis:
